### ISSUE TITLE
Can't instantiate abstract class Experiment with abstract methods episode, frame, test, train

### ISSUE THREAD

**Issue by fatemehN** [cpnota/all-example-project#2]
Hi,
I followed your instructions and got this error: 

```
$ python main.py Pong
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    run()
  File "main.py", line 26, in run
    Experiment(model_predictive_dqn(device=args.device), env, frames=args.frames)
TypeError: Can't instantiate abstract class Experiment with abstract methods episode, frame, test, train
```
Do you know what is the problem?

**Comment by cpnota** [comment]
Oops! This needs some tweaks to match the new release of the core library. Thanks for raising the issue! I'll update it in the morning!

**Comment by cpnota** [comment]
Alright, should be fixed with latest commit. Let me know if you are still having problems!
